### ISSUE TITLE
rake aborted! variable @base is undefined

### ISSUE THREAD

**Issue by patrickespake** [reflection/designmodo-flatuipro-rails#21]
I had this problem when I run RAILS_ENV=production rake assets:precompile

```
...
rake aborted!
variable @base is undefined
  (in /Users/patrickespake/Projetos/coursify/lib/assets/Flat-UI/HTML/UI/less/mixins.less)
at /Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/less-2.4.0/lib/less/js/lib/less/parser.js:424:31
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/less-
...
```

Full trace: 

```
➜  coursify git:(landing_page) ✗ RAILS_ENV=production rake assets:precompile
I, [2013-10-27T05:44:56.206120 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/background-84fadf8fd2e5a3631172acdabfd07945.jpg
I, [2013-10-27T05:44:56.289013 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/landing_page/bg-84fadf8fd2e5a3631172acdabfd07945.jpg
I, [2013-10-27T05:44:56.296731 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/landing_page/bg-589d5985b06d70093c8e0562839c001d.png
I, [2013-10-27T05:44:56.325899 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/landing_page/favicon-fecbc53a6a238d69ffe4f83b5a62d178.png
I, [2013-10-27T05:44:56.353211 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/landing_page/logo-5c8621719b6cb0e1299cb3d02fba3a11.png
I, [2013-10-27T05:44:56.355703 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/logo-4d035bbf7352f2073cddb052ae9d8851.png
I, [2013-10-27T05:44:56.358104 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/rails-1a1ca78f5753b7fe0e44812de505bf4d.png
I, [2013-10-27T05:45:02.247947 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/application-ff8b026064117649e017a4804005efbe.js
I, [2013-10-27T05:45:05.942824 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/backoffice-6b1284912d2dd427d9e352f178096f0e.js
I, [2013-10-27T05:45:05.953988 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/backoffice/bootstrap-77f19263b1f157ba47cd3850e96275b5.js
I, [2013-10-27T05:45:05.958196 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/backoffice/screen-5fa627b0e683cca9b500d2c8abc7ae90.js
I, [2013-10-27T05:45:05.963086 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/bootstrap-551e4b191b768b9a0aab22704084f907.js
I, [2013-10-27T05:45:05.997221 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/flatuipro-d6aecf773dfeb7e56a6bd79536147aca.js
I, [2013-10-27T05:45:06.002133 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/frontend/screen-5fa627b0e683cca9b500d2c8abc7ae90.js
I, [2013-10-27T05:45:16.675434 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/landing_page-51e6b6441d6a70fd953e0df11e36f517.js
I, [2013-10-27T05:45:16.694103 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/landing_page/screen-5fa627b0e683cca9b500d2c8abc7ae90.js
I, [2013-10-27T05:45:19.948543 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/application-877dfc7446fae585437079cdc960050a.css
I, [2013-10-27T05:45:21.389474 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/backoffice-5ae502b17bdd585f7626ec169e4379bf.css
I, [2013-10-27T05:45:21.468812 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/backoffice/bootstrap_and_overrides-5ae502b17bdd585f7626ec169e4379bf.css
I, [2013-10-27T05:45:21.480440 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/backoffice/screen-58c7c0e35a67f189e19b8c485930e614.css
I, [2013-10-27T05:45:21.484892 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/bootstrap_and_overrides-15d0ad0abc520136e8eba0cf8b0f21c3.css
I, [2013-10-27T05:45:22.577676 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/flatuipro-11e50340831b626bf649ad1469b63ac1.css
I, [2013-10-27T05:45:22.587380 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/flatuipro_custom/config-58c7c0e35a67f189e19b8c485930e614.css
I, [2013-10-27T05:45:22.594464 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/frontend/landing_page-3b5a17cdbd19829b6db6291026c638e5.css
I, [2013-10-27T05:45:22.600654 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/frontend/landing_page_custom-76f5a959ad0bc18f06a0bb9244b34a9c.css
I, [2013-10-27T05:45:25.627647 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/landing_page-e6989edb4de6d44f2e7c42e984f38759.css
I, [2013-10-27T05:45:25.645600 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/landing_page/backdrop-a2aaa8b5f3f47808aac58334af62737d.css
I, [2013-10-27T05:45:25.652154 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/landing_page/body-0ee6437b22b73802bf18874aa8ead926.css
I, [2013-10-27T05:45:25.658051 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/landing_page/form-c0b6a9af742c1e8ed96896bfb4398122.css
I, [2013-10-27T05:45:25.665414 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/landing_page/navbar-065102430936406cd80b85ae75e59c61.css
I, [2013-10-27T05:45:25.671739 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/landing_page/responsive-32dadf299ada8b7dbcb96bba72d5534c.css
I, [2013-10-27T05:45:25.679026 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/bootstrap/css/bootstrap-docs-f846b023201c67d5c8863a00d4474afb.css
I, [2013-10-27T05:45:25.687032 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/bootstrap/css/bootstrap-responsive-37de205478ae27e0b81e67ee8ffa4fa9.css
I, [2013-10-27T05:45:25.741096 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/bootstrap/css/bootstrap-d5fbd360cfd684518c74d35ba38427f0.css
I, [2013-10-27T05:45:25.752712 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/bootstrap/css/prettify-e76dc5715346a6e478aaaf59cb08004d.css
I, [2013-10-27T05:45:25.760841 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/bootstrap/js/application-d2d90414fb1bb2e7b11c5aa8c4e77d76.js
I, [2013-10-27T05:45:25.777798 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/bootstrap/js/google-code-prettify/prettify-6220d92d21b31b0e05c4deb58efd3fd2.js
I, [2013-10-27T05:45:25.788792 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/bootstrap/js/holder-9cbff632e4cd7bcbd41147e85b35c435.js
I, [2013-10-27T05:45:25.796365 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/css/demo-c2eb55603fabfd518ab0edb6f1fd6a33.css
I, [2013-10-27T05:45:25.807241 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/css/flat-ui-79d17e8230d04e82f20d667a36071bc5.css
I, [2013-10-27T05:45:25.821956 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/js/application-6755a7cf57742d64c4a14dd2b1f11bd0.js
I, [2013-10-27T05:45:25.829898 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/js/bootstrap-select-5b624be49d02648e7519a9079f2bb719.js
I, [2013-10-27T05:45:25.871908 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/js/bootstrap-switch-32842ae48d44e4eacda0bf29a1c7e820.js
I, [2013-10-27T05:45:25.879982 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/js/bootstrap.min-406bdd990fd8a1fc1c381cc8d4b2b1be.js
I, [2013-10-27T05:45:25.888798 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/js/flatui-checkbox-6612cd155289809becd6cd9c1cade001.js
I, [2013-10-27T05:45:25.898810 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/js/flatui-radio-3a336968c7e76192147dba7f00c85646.js
I, [2013-10-27T05:45:25.923677 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/js/html5shiv-c9f1d1f6a558e92423e3036f57ca60c2.js
I, [2013-10-27T05:45:25.936757 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/js/icon-font-ie7-ef15d3c0233f259949c27598a193a6d8.js
I, [2013-10-27T05:45:25.949386 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/js/jquery-1.8.3.min-88350b72942996517ccc88c3f665c4d8.js
I, [2013-10-27T05:45:25.967731 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/js/jquery-ui-1.10.3.custom.min-fff3f018d16268fb08e2ef16a3c2ce9f.js
I, [2013-10-27T05:45:26.015434 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/js/jquery.placeholder-143cccbc7e3a58c285818d2fcd6b416b.js
I, [2013-10-27T05:45:26.030370 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/js/jquery.stacktable-7dc104683009e5ac9265115fb2bfe3ab.js
I, [2013-10-27T05:45:26.040861 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/js/jquery.tagsinput-b063a6e409fc595ed1447e4073ef94aa.js
I, [2013-10-27T05:45:26.050481 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/js/jquery.ui.touch-punch.min-4508b54ede0d3ef993d22f14f1bc8f15.js
I, [2013-10-27T05:45:26.060690 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/less/config-58c7c0e35a67f189e19b8c485930e614.css
I, [2013-10-27T05:45:26.072338 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/less/demo-c2eb55603fabfd518ab0edb6f1fd6a33.css
I, [2013-10-27T05:45:26.084666 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/less/flat-ui-79d17e8230d04e82f20d667a36071bc5.css
I, [2013-10-27T05:45:26.099668 #69306]  INFO -- : Writing /Users/patrickespake/Projetos/coursify/public/assets/HTML/UI/less/icon-font-748c0985c7d590320a024fe2fb676f52.css
rake aborted!
variable @base is undefined
  (in /Users/patrickespake/Projetos/coursify/lib/assets/Flat-UI/HTML/UI/less/mixins.less)
at /Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/less-2.4.0/lib/less/js/lib/less/parser.js:424:31
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/less-2.4.0/lib/less/parser.rb:100:in `block in to_css'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/less-2.4.0/lib/less/java_script/v8_context.rb:90:in `block in do_lock'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/less-2.4.0/lib/less/java_script/v8_context.rb:88:in `call'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/less-2.4.0/lib/less/java_script/v8_context.rb:88:in `Locker'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/less-2.4.0/lib/less/java_script/v8_context.rb:88:in `do_lock'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/less-2.4.0/lib/less/java_script/v8_context.rb:60:in `lock'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/less-2.4.0/lib/less/java_script/v8_context.rb:30:in `exec'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/less-2.4.0/lib/less/java_script.rb:26:in `exec'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/less-2.4.0/lib/less/parser.rb:100:in `to_css'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/less-rails-2.4.2/lib/less/rails/template_handlers.rb:19:in `evaluate'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/context.rb:197:in `block in evaluate'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/context.rb:194:in `each'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/context.rb:194:in `evaluate'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/processed_asset.rb:12:in `initialize'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/base.rb:374:in `new'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/base.rb:374:in `block in build_asset'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/base.rb:395:in `circular_call_protection'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/base.rb:373:in `build_asset'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/index.rb:94:in `block in build_asset'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/caching.rb:58:in `cache_asset'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/index.rb:93:in `build_asset'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/base.rb:287:in `find_asset'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/index.rb:61:in `find_asset'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/bundled_asset.rb:37:in `init_with'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/asset.rb:24:in `from_hash'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/caching.rb:54:in `cache_asset'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/index.rb:93:in `build_asset'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/base.rb:287:in `find_asset'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/index.rb:61:in `find_asset'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/manifest.rb:211:in `block in find_asset'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/manifest.rb:257:in `benchmark'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/manifest.rb:210:in `find_asset'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/manifest.rb:119:in `block in compile'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/manifest.rb:118:in `each'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/sprockets/manifest.rb:118:in `compile'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-rails-2.0.1/lib/sprockets/rails/task.rb:60:in `block (3 levels) in define'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-2.10.0/lib/rake/sprocketstask.rb:146:in `with_logger'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/gems/sprockets-rails-2.0.1/lib/sprockets/rails/task.rb:59:in `block (2 levels) in define'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/bin/ruby_executable_hooks:15:in `eval'
/Users/patrickespake/.rvm/gems/ruby-1.9.3-p448@coursify_landing_page/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

My Gemfile:

```
source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# Use mysql as the database for Active Record
gem 'mysql2'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer'

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
gem 'jquery-turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
gem 'capistrano', group: :development
gem 'flowdock'

# Use debugger
# gem 'debugger', group: [:development, :test]

gem 'less'
gem 'less-rails'
gem 'twitter-bootstrap-rails'
gem 'jquery-ui-rails'
gem 'designmodo-flatuipro-rails'
gem 'haml-rails'
gem 'haml_assets'
gem 'exception_notification', '~> 4.0.0'
gem 'rails-i18n', '~> 4.0.0.pre'
gem 'devise'
gem 'simple_form'
gem 'daemons'
gem 'delayed_job_active_record'
gem 'compass-rails', github: "Compass/compass-rails", branch: "rails4-hack"
gem 'poltergeist'
gem 'instrumental_agent'
gem 'protected_attributes'
gem 'valid_email'
gem 'kaminari'

group :development, :test do
  gem 'debugger'
  gem 'delorean'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry'
  gem 'pry-rails'
  gem 'rspec'
  gem 'rspec-rails', '~> 2.12'
  gem 'capybara'
  gem 'launchy'
end

group :development do
  gem 'bullet'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'letter_opener'
end

group :test do
  gem 'coveralls', require: false
  gem 'database_cleaner'
  gem 'email_spec'
  gem 'selenium-webdriver'
  gem 'simplecov', require: false
  gem 'webmock', require: false
  gem 'shoulda-matchers'
end

group :staging, :production do
  gem 'rails_12factor'
end
```

How I can resolve it?

**Comment by patrickespake** [comment]
Any idea?
Why the support is too slow for PRO users?

**Comment by reflection** [comment]
Hi Patrick,

1)  I'm not at all affiliated with Designmodo... so if you want "official PRO" support ask them directly: https://github.com/designmodo/Flat-UI-Pro-Support
2)  Since you're not using my gem correctly (you copied over the Flat UI assets manually to your app), why are you asking for support here?  Either let this gem manage integration into the Rails Asset Pipeline or do it yourself.

Sam
