### ISSUE TITLE
Flat UI Pro 1.3.0 known issues

### ISSUE THREAD

**Issue by reflection** [reflection/designmodo-flatuipro-rails#29]
Hi all,

The 1.3.0 release has some issues I'd like to highlight:
- On the demo page, the video poster image won't work.  This is because the <video> tag needs to be rewritten with the rails helper video_tag (you can do this yourself if you wish; I felt it wasn't worth the effort): http://api.rubyonrails.org/classes/ActionView/Helpers/AssetTagHelper.html#method-i-video_tag .
- The OFF switches on the demo page are offset incorrectly (hopefully I'll find time later to figure out why and fix these).

Also, in case you want a quick way to get started with Flat UI Pro 1.3.0 in Rails with Bootstrap 3:

``` bash
$ rails new frodo
$ cd frodo/
$ echo -e "gem 'therubyracer'\ngem 'jquery-ui-rails'\ngem 'less-rails-bootstrap'" >> Gemfile
$ bundle install

# Add these lines to setup less-rails-bootstrap (via sed or favorite text editor)
#
# In app/assets/javascripts/application.js (AFTER "require jquery")
# Add //= require twitter/bootstrap
#
# In app/assets/stylesheets/application.css (BEFORE "require tree")
# Add *= require twitter/bootstrap

$ echo -e "gem 'designmodo-flatuipro-rails', '~> 1.3.0.0.branch'\n" >> Gemfile
$ bundle install

# Change the following path to wherever your Flat UI Pro 1.3.0 directory is located
$ cd ~/Developer/flatuipro-1.3.0
$ cd HTML/UI/Flat-UI-Pro-1.3.0/
$ bower install

# Change back to the frodo directory
$ cd ~/Developer/frodo
$ rails g flatuipro:install ~/Developer/flatuipro-1.3.0/
$ rails g flatuipro:demo
```

**Comment by a14m** [comment]
Trying to deploy to heroku... I always get the following 

```
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       I, [2014-09-11T04:43:38.436644 #647]  INFO -- : Loading Rails (4.1.5) integration
       rake aborted!
       Sprockets::FileNotFound: couldn't find file 'fileinput'
       (in /tmp/build_6171bf2d-98ce-4e8c-bb58-64ebb745f8a4/app/assets/javascripts/flatuipro.js:1)
       /tmp/build_6171bf2d-98ce-4e8c-bb58-64ebb745f8a4/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/context.rb:106:in `resolve'
       /tmp/build_6171bf2d-98ce-4e8c-bb58-64ebb745f8a4/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/context.rb:146:in `require_asset'
      ..... many many lines :D 
```

**Comment by jhchabran** [comment]
@artmees Once you installed the _flatuipro_ assets, you can deploy it to heroku by unpacking the gem in your vendor/gems directory. Be sure it is versioned or you won't get it on heroku. Then add the following line to your gemfile : 

``` ruby
gem 'designmodo-flatuipro-rails', '1.3.0.0.branch', path: 'vendor/gems/designmodo-flatuipro-rails-1.3.0.0.branch'
```

I had a small issue while unpacking the gem, apparently `google.svg` was a symlink and I had a weird `google\ .svg` file in the assets. I removed the symlink and put the real google.svg file in its place and it's now perfectly working on heroku. 

Downside is you'll have to manually update the vendored gem.

**Comment by nakita5648** [comment]
Trying to deploy to heroku... I always get the followingremote:        rake aborted!
remote:        Sprockets::FileNotFound: couldn't find file 'fileinput' with type 'application/javascript'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/app/assets/javascripts/flatuipro.js:1
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/resolve.rb:64:in `resolve!'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/directive_processor.rb:399:in `resolve'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/directive_processor.rb:207:in `process_require_directive'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/directive_processor.rb:180:in `block in process_directives'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/directive_processor.rb:178:in `each'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/directive_processor.rb:178:in `process_directives'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/directive_processor.rb:83:in `_call'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/directive_processor.rb:68:in `call'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/loader.rb:86:in `load_asset_by_uri'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/loader.rb:45:in `block in load'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/loader.rb:155:in `fetch_asset_from_dependency_cache'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/loader.rb:38:in `load'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/cached_environment.rb:47:in `yield'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/cached_environment.rb:47:in `load'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/bundle.rb:23:in `block in call'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/utils.rb:183:in `dfs'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/bundle.rb:24:in `call'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/loader.rb:86:in `load_asset_by_uri'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/loader.rb:45:in `block in load'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/loader.rb:155:in `fetch_asset_from_dependency_cache'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/loader.rb:38:in `load'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/cached_environment.rb:47:in `yield'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/cached_environment.rb:47:in `load'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/base.rb:63:in `find_asset'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/base.rb:70:in `find_all_linked_assets'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/manifest.rb:138:in `block in find'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:223:in `block in stat_tree'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:207:in `block in stat_directory'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:204:in `each'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:204:in `stat_directory'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:222:in `stat_tree'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:105:in `each'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:105:in `block in logical_paths'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:104:in `each'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:104:in `logical_paths'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/manifest.rb:136:in `find'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/sprockets/manifest.rb:162:in `compile'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-rails-2.3.2/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-3.2.0/lib/rake/sprocketstask.rb:147:in `with_logger'
remote:        /tmp/build_470658e91113d9d2a2975eeb56805596/vendor/bundle/ruby/2.0.0/gems/sprockets-rails-2.3.2/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
remote:        Tasks: TOP => assets:precompile
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote: 
remote:  !     Push rejected, failed to compile Ruby app
remote: 
remote: Verifying deploy....
remote: 
remote: !       Push rejected to blooming-basin-7075.
remote:
