### ISSUE TITLE
Navbar dropdown menus not working on iPad and iPhone

### ISSUE THREAD

**Issue by patrickespake** [reflection/designmodo-flatuipro-rails#30]
You can see the old information here: https://github.com/designmodo/Flat-UI-Pro-Support/issues/483

I updated to this version:

```
gem 'designmodo-flatuipro-rails', '~> 1.3.0.0.branch'
```

When I restart the rails server I got this error:

```
Sprockets::FileNotFound - couldn't find file 'flat-ui'
  (in /Users/patrickespake/Projects/coursify/app/assets/stylesheets/customer.css:4):
  sprockets (2.11.0) lib/sprockets/context.rb:106:in `resolve'
  sprockets (2.11.0) lib/sprockets/context.rb:146:in `require_asset'
  sprockets (2.11.0) lib/sprockets/directive_processor.rb:217:in `process_require_directive'
  sprockets (2.11.0) lib/sprockets/directive_processor.rb:167:in `block in process_directives'
  sprockets (2.11.0) lib/sprockets/directive_processor.rb:165:in `process_directives'
  sprockets (2.11.0) lib/sprockets/directive_processor.rb:99:in `evaluate'
  tilt (1.4.1) lib/tilt/template.rb:103:in `render'
```

After that I tried to reinstall the Flat UI Pro again and I got this error:

```
➜  coursify git:(master) ✗ pwd=$(pwd)
➜  ~pwd git:(master) ✗ flatui_path="/lib/assets/Flat-UI/"
➜  ~pwd git:(master) ✗ bundle exec rails generate flatuipro:install $pwd$flatui_path
/Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/gems/designmodo-flatuipro-rails-1.3.0.0.branch/lib/generators/flatuipro/install/install_generator.rb:22:in `copy_assets': Invalid Flat UI Pro directory (RuntimeError)
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/gems/railties-4.1.6/lib/rails/generators.rb:157:in `invoke'
```

**Comment by patrickespake** [comment]
Please, How can I resolve this?
