### ISSUE TITLE
Problem to install Flat UI Pro 1.3.0

### ISSUE THREAD

**Issue by patrickespake** [reflection/designmodo-flatuipro-rails#31]
I got for install the Flat UI Pro 1.3.0:

```
➜  coursify git:(master) ✗ rails generate flatuipro:install "/Users/patrickespake/Projects/coursify/lib/assets/Flat UI HTML - Personal License"
/Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/gems/designmodo-flatuipro-rails-1.3.0.0.branch/lib/generators/flatuipro/install/install_generator.rb:25:in `copy_assets': 'bower install' must be run first to fetch javascript dependencies (RuntimeError)
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/patrickespake/.rvm/gems/ruby-2.1.3@coursify/gems/railties-4.1.7/lib/rails/generators.rb:157:in `invoke'
```

My Gemfile:

```
source 'https://rubygems.org'

ruby '2.1.3'

gem 'rails', '4.1.7'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyracer'
gem 'jquery-rails', '3.1.1'
gem 'turbolinks'
gem 'jquery-turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'unicorn'
gem 'less'
gem 'less-rails'
gem 'twitter-bootstrap-rails'
gem 'jquery-ui-rails', '5.0.0'
gem 'designmodo-flatuipro-rails', '1.3.0.0.branch'
gem 'haml-rails'
gem 'haml_assets'
gem 'rails-i18n', '~> 4.0.0.pre'
gem 'devise'
gem 'simple_form'
gem 'daemons'
gem 'compass-rails'
gem 'protected_attributes'
gem 'valid_email'
gem 'kaminari'
gem 'cindy'
gem 'state_machine'
gem 'newrelic_rpm'
gem 'friendly_id', '~> 5.0.0'
gem 'dropbox-sdk'
gem 'youtube_it', '~> 2.4.2'
gem 'rmagick', require: 'RMagick'
gem 'remotipart', '~> 1.2'
gem 'carrierwave'
gem 'fog'
gem 'chronic_duration'
gem 'google_visualr'
gem 'bootstrap-sass', '~> 3.3.1.0'
gem 'autoprefixer-rails'
gem 'delayed_job_active_record'

group :doc do
  gem 'sdoc', '~> 0.4.0'
end

group :development, :test do
  gem 'byebug'
  gem 'delorean'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry'
  gem 'pry-rails'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'launchy'
end

group :development do
  gem 'spring'
  gem 'bullet'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'letter_opener'
  gem 'capistrano'
end

group :test do
  gem 'minitest'
  gem 'coveralls', require: false
  gem 'database_cleaner'
  gem 'email_spec'
  gem 'selenium-webdriver'
  gem 'simplecov', require: false
  gem 'webmock', require: false
  gem 'shoulda-matchers'
  gem 'poltergeist'
  gem 'capybara'
end

group :staging, :production do
  gem 'rails_12factor'
end
```

How can I fix it?

**Comment by mikebutts** [comment]
I'm having the same problem, I've tried absolute paths and relative. Also tried to move the folder in different locations. stuck.

**Comment by ryanrussell** [comment]
Same issue. Any ideas? I'm unable to install...

$ rails generate flatuipro:install /Path/To/FlatUI
/home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/designmodo-flatuipro-rails-1.3.0.0.branch/lib/generators/flatuipro/install/install_generator.rb:25:in `copy_assets': 'bower install' must be run first to fetch javascript dependencies (RuntimeError)
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in`block in invoke_all'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in`map'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/group.rb:232:in`dispatch'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/generators.rb:157:in`invoke'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/commands/generate.rb:11:in `<top (required)>'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in`require'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in`load_dependency'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:135:in`generate_or_destroy'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:51:in `generate'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:40:in`run_command!'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/commands.rb:17:in `<top (required)>'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in`require'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in`load_dependency'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
        from /home/ubuntu/usaspending/bin/rails:8:in`<top (required)>'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in `load'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in`block in load'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in`load'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
        from -e:1:in `<main>'

ubuntu@ip-10-65-128-160:~/usaspending$ ruby -v
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-linux]

ubuntu@ip-10-65-128-160:~/usaspending$ rails -v
Rails 4.1.6

**Comment by ryanrussell** [comment]
Oh. Simple...

sudo apt-get install bower
cd /path/to/extracted-flatui/HTML/UI/Flat-UI-Pro-1.3.0/ #Or Branch you're using
bower install

Hope this helps the next guy in a hurry
