### ISSUE TITLE
Error running generator after updating to rails 4.2 

### ISSUE THREAD

**Issue by dunnston** [reflection/designmodo-flatuipro-rails#32]
I am getting the following error when trying to run the generator after updating ruby to 2.2.0 and rails to 4.2. 

 gsub  /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/designmodo-flatuipro-rails-1.3.2.0.branch/app/assets/less/variables.less
/Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:231:in `binread': No such file or directory @ rb_sysopen - /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/designmodo-flatuipro-rails-1.3.2.0.branch/app/assets/less/variables.less (Errno::ENOENT)
        from /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:231:in`gsub_file'
        from /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/designmodo-flatuipro-rails-1.3.2.0.branch/lib/generators/flatuipro/install/install_generator.rb:103:in `patch_assets'
        from /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
        from /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in`block in invoke_all'
        from /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in`map'
        from /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in`dispatch'
        from /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/generators.rb:157:in`invoke'
        from /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands/generate.rb:13:in `<top (required)>'
        from /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in`require'
        from /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
        from /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in`load_dependency'
        from /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
        from /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:123:in`require_command!'
        from /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
        from /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:50:in`generate'
        from /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in`<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in`<main>'

**Comment by reflection** [comment]
Hi dunnston,

I _think_ you have to re-run the install generator because upgrading ruby means a new gems directory, which also means that the Flat UI Pro assets need to be copied over again.

**Comment by dunnston** [comment]
Thanks for responding so quickly. Unfortunately, that
is where I am running to to trouble. I get the error during the installation when attempting to re-run the generator.

**Comment by dunnston** [comment]
It's been almost a year and I am still getting the same exact error. Any ideas on how to fix this?

**Comment by dunnston** [comment]
I think I may have finally figured it out. Looking at this line /Users/ryandunn/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/designmodo-flatuipro-rails-1.3.2.0.branch/app/assets/less/variables.less  I suspect it is not able to find the variables.less files. I looked in the directly and it was not there instead there was a Users folder there that restarted the entire file path back to the file. I copied the files into the less directory and tried reinstalling. I did not get an error this time.
