### ISSUE TITLE
heroku run rake assets:precompile Sprockets::FileNotFound: couldn't find file 'fileinput'

### ISSUE THREAD

**Issue by tsaifi9** [reflection/designmodo-flatuipro-rails#33]
gem 'designmodo-flatuipro-rails', '~> 1.3.2.0.branch'

been having issue with this gem on heroku. I followed the instructions of first precompiling it locally and then pushing it to heroku, but my fonts (lato) and my images (flat-ui-pro-icons-regular.ttf) are not loading.

I then tried to go onto my heroku server and run: heroku run rake assets:precompile

but got the error:
rake aborted!
Sprockets::FileNotFound: couldn't find file 'fileinput'
  (in /app/app/assets/javascripts/flatuipro.js:1)
/app/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/context.rb:106:in `resolve'
/app/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/context.rb:146:in`require_asset'
/app/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/directive_processor.rb:217:in `process_require_directive'
/app/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.3/lib/sprockets/directive_processor.rb:167:in`block in process_directives'
/app/vendor/bundle/ruby/2.2.0/gems/sprocket
...

**Comment by tsaifi9** [comment]
Fixed.
- Added production database (previously only had development and test db) in config/database.yml 
- reran assets:precompile
- pushed to heroku and it worked
