### ISSUE TITLE
install flat ui pro

### ISSUE THREAD

**Issue by lostpupil** [reflection/designmodo-flatuipro-rails#35]
run the following command 
`rails g flatuipro:install "/Users/crazyphage/Desktop/Flat UI HTML - Developers License"`
will crash 

```
Users/crazyphage/.rvm/gems/ruby-2.1.3/gems/designmodo-flatuipro-rails-1.1.4.2/lib/generators/flatuipro/install/install_generator.rb:22:in `copy_assets': Invalid Flat UI Pro directory (RuntimeError)
	from /Users/crazyphage/.rvm/gems/ruby-2.1.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/crazyphage/.rvm/gems/ruby-2.1.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/crazyphage/.rvm/gems/ruby-2.1.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/crazyphage/.rvm/gems/ruby-2.1.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/crazyphage/.rvm/gems/ruby-2.1.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/crazyphage/.rvm/gems/ruby-2.1.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/crazyphage/.rvm/gems/ruby-2.1.3/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/crazyphage/.rvm/gems/ruby-2.1.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/crazyphage/.rvm/gems/ruby-2.1.3/gems/railties-4.2.0/lib/rails/generators.rb:157:in `invoke'
	from /Users/crazyphage/.rvm/gems/ruby-2.1.3/gems/railties-4.2.0/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /Users/crazyphage/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/crazyphage/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/crazyphage/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/crazyphage/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/crazyphage/.rvm/gems/ruby-2.1.3/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /Users/crazyphage/.rvm/gems/ruby-2.1.3/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
	from /Users/crazyphage/.rvm/gems/ruby-2.1.3/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /Users/crazyphage/.rvm/gems/ruby-2.1.3/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/crazyphage/.rvm/gems/ruby-2.1.3/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by lostpupil** [comment]
![image](https://cloud.githubusercontent.com/assets/2015695/7364908/3a59d37e-edbe-11e4-833a-499a04ac3262.png)
but after i can install it i got the page with awful look

**Comment by lostpupil** [comment]
![image](https://cloud.githubusercontent.com/assets/2015695/7364929/53d709de-edbe-11e4-85f5-e3bcf87b434f.png)

**Comment by reflection** [comment]
Sorry for taking so long to respond, but I'm fairly sure you're probably using the wrong branch.  Try the instructions here: https://github.com/reflection/designmodo-flatuipro-rails/tree/flatuipro-1.3

**Comment by lostpupil** [comment]
well i am using the right branch, coz I have already tried several times, but nothing works for me, just get the error in console.
![image](https://cloud.githubusercontent.com/assets/2015695/7468274/ef76b5d6-f338-11e4-94ab-0545b036c3d6.png)

**Comment by reflection** [comment]
If you google your error... somehow your jquery is messed up.  Are you loading it twice in your pipeline somehow (or manually in the wrong place)?

http://stackoverflow.com/questions/15932553/typeerror-popover-is-not-a-function-bootstrap-issues

**Comment by lostpupil** [comment]
well can you show me your demo project application.css and application.js file? I must missed some action.
here is my application.js
```javascript
//= require jquery
//= require jquery-ui
//= require flatuipro
//= require jquery_ujs
//= require twitter/bootstrap
//= require turbolinks
//= require_tree .
```
and my css
```css
 *= require_tree .
 *= require_self
```

or can you create a demo project?
Yesterday, I found something acting weird for the demo page generator.
The css works fine.
